In [1]:
import pandas as pd
from pandas import Series,DataFrame

In [2]:
obj=pd.Series([4,7,-5,3])
obj # 인덱스와 데이터 같이 저장

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values # Data 객체 반환

array([ 4,  7, -5,  3])

In [4]:
obj.index # index 객체 반환

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2=pd.Series([4,7,-5,3],index=['d','b','a','c']) # 인덱스 지정 가능

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2['a']

-5

In [9]:
obj2['d']=6 # Data 변경 가능
obj2['d']

6

In [10]:
obj2[['c','a','d']] # ['c','a','d'] 는 여기서 index 배열로 해석된다.

c    3
a   -5
d    6
dtype: int64

In [11]:
obj2[obj2>0] # Boolean 배열을 사용해서 값을 걸러내거나 Numpy 배열 연산을 수행해도 index-value 연결이 유지된다.

d    6
b    7
c    3
dtype: int64

In [12]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [13]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [14]:
'b' in obj2

True

In [15]:
'e' in obj2

False

In [16]:
sdata={'Ohio':3500,'Texas':71000,'Oregon':16000,'Utah':5000} # python dictionary 로 부터 Series 객체 생성 가능
obj3=pd.Series(sdata)
obj3

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [17]:
states=['California','Ohio','Oregon','Texas']
obj4=pd.Series(sdata,index=states)

In [18]:
obj4 # 'California' 에 대한 값은 찾을 수 없기 때문에 NaN(Not a Number)로 표시된다. 'Utah'는 states에 포함되어 있지 않으므로 빠졌다.

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [21]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
obj3+obj4 # Series 의 유용한 기능은 산술 연산에서 색인과 라벨로 자동 정렬하는 것이다.

California         NaN
Ohio            7000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [23]:
obj4.name='population'
obj4.index.name='state'
obj4

state
California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [24]:
# DataFrame
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
      'year': [2000,2001,2002,2001,2002,2003],
      'pop': [1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data) # 만들어진 DataFrame의 index는 Series와 같은 방식으로 자동으로 대입되며 컬럼은 정렬되어 저장된다.

In [25]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [26]:
frame.head() # 큰 DataFrame을 다룰 때는 head 메서드를 이용해서 처음 5개의 로우만 출력할 수도 있다. 

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [27]:
pd.DataFrame(data,columns=['year','state','pop']) # 원하는 순서대로 column을 저장하면 원하는 순서를 가진 DataFrame 객체가 생성된다.

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [28]:
frame2=pd.DataFrame(data, columns=['year','state','pop','debt'], # 사전에 없는 값을 넘기면 결측치로 저장된다.
                    index=['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [29]:
frame['state'] # DataFrame의 컬럼은 Series처럼 사전 형식의 표기법으로 접근하거나 속성 형식으로 접근할 수있다.

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [30]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [31]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [32]:
frame2.loc['three'] # Row는 위치나 loc 속성을 이용해서 이름을 통해 접근할 수 있다.

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [33]:
frame2['debt']=16.5 # 컬럼은 대입이 가능하다.
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [34]:
frame2['debt']=np.arange(6.)

In [35]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [36]:
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])
frame2['debt']=val # Series를 대입하면 DataFrame의 index 값에 따라 값이 대입되며 존재하지 않는 index에는 결측치가 대입된다.
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [37]:
frame2['eastern']=frame2.state=='Ohio' # 존재하지 않는 컬럼을 대입하면 새로운 컬럼을 생성한다.
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [38]:
del frame2['eastern'] # del 예약어를 이용해서 컬럼을 삭제할 수 있다.

In [39]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [40]:
pop={'Nevada':{2001:2.4, 2002:2.9}, # 중첩된 dictionary를 이용해서 데이터를 생성할 수 있다.
     'Ohio':{2000:1.5, 2001:1.7,  2002:3.6}}
frame3=pd.DataFrame(pop) # 바깥에 있는 key는 column이 되고 안쪽의 key는 row가 된다.
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [41]:
frame3.T # 데이터를 Transpose 할 수 있다.

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [42]:
pd.DataFrame(pop, index=[2001,2002,2003]) # index를 직접 지정할 수 있다.

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [43]:
pdata={'Ohio':frame3['Ohio'][:-1], # Series 객체를 담고 있는 사전 데이터도 같은 방식으로 취급된다.
       'Nevada':frame3['Nevada'][:-1]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [44]:
frame3.index.name='year' # DataFrame의 index와 columns에 name 속성을 지정했다면 이 역시 함께 출력된다.
frame3.columns.name='state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [45]:
frame3.values # values 속성은 저장된 데이터를 2차원 배열로 반환한다.

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [46]:
frame2.values # DataFrame의 컬럼이 서로 다른 dtype을 가지고 있다면 모든 컬럼을 수용하기 위해 그 컬럼의 배열의 dtype이 선택된다.

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [47]:
# index object 
obj=pd.Series(range(3), index=['a','b','c']) # pandas의 index 객체는 각 row와 column에 대한  이름과 다른 메타데이터(축의 이름 등)을
index=obj.index                              # 저장하는 객체다.

In [48]:
index

Index(['a', 'b', 'c'], dtype='object')

In [49]:
index[1]='d' # index 객체는 변경이 불가능하다.

TypeError: Index does not support mutable operations

In [50]:
labels=pd.Index(np.arange(3)) # 자료구조 사이에서 안전하게 공유될 수 있다.
obj2=pd.Series([1.5, -2.5,  0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [51]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [52]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [53]:
'Ohio' in frame3.columns

True

In [54]:
2003 in frame3.index

False

In [55]:
dup_labels=pd.Index(['foo', 'foo', 'bar', 'bar']) # pandas의 index는 중복되는 값을 허용한다.
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [58]:
# reindex
obj=pd.Series([4.5,7.2,-5.3,3.6], index=['d','b','a','c'])
obj2=obj.reindex(['a','b','c','d','e'])

In [59]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [72]:
# method='ffill'
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3=obj3.reindex(range(6),method='ffill')
obj3

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [73]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)), # DataFrame은 로우, 컬럼 둘다 reindex 가능하다.
                   index=['a','c','d'],
                   columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [74]:
frame2=frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [75]:
# 컬럼은 예약어를 사용할 수 있다.
states=['Texas','Utah','California']
frame=frame.reindex(columns=states)
frame

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [77]:
# loc를 사용하면 조금 더 간결하고 명시적으로 사용할 수 있다.
frame.loc[['a','c','d'],states]


Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [78]:
# drop 메서드를 사용해서 로우나 컬럼을 삭제 할 수 있다.
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [79]:
new_obj=obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [82]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                  index=['Ohio', 'Colorado', 'Utah', 'New York'],
                  columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [83]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [84]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [85]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [87]:
# loc, iloc 선택하기
# 축 이름을 선택할 때는 loc, 정수 index로 선택할 때는 iloc
data.loc['Colorado',['two','three']]


two      5
three    6
Name: Colorado, dtype: int64

In [88]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [89]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [91]:
# 산술 연산
# Series
s1=pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2=pd.Series([-2.1,3.6,-1.5,4,3.1],
             index=['a','c','e','f','g'])

In [92]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [93]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [94]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [95]:
# DataFrame
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),
                 columns=list('bcd'),
                 index=['Ohio','Texas','Colorade'])
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),
                 columns=list('bde'),
                 index=['Utah','Ohio','Texas','Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorade  6.0  7.0  8.0

In [96]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [97]:
df1+df2 # 교집합

b   c     d   e
Colorade  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [99]:
df1=pd.DataFrame({'A':[1,2]})
df2=pd.DataFrame({'B':[3,4]})

In [100]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [103]:
# 산술 연산 메서드에 채워 넣을 값 지정하기
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),
                 columns=list('abcd'))
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),
                 columns=list('abcde'))
df2.loc[1,'b']=np.nan

In [104]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [105]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [106]:
df1+df2 # 겹치지 않는 부분은 NA 값이 된다.

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [107]:
df1.add(df2,fill_value=0) # df1에 df2 데이터 값을 더하고 존재 하지 않는 index는 df2로 채움

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0